interface CountryEntry {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: CountryEntry[] = [
  { code: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "CD", name: "RD Congo", flag: "🇨🇩" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "CM", name: "Cameroun", flag: "🇨🇲" },
  { code: "CF", name: "Centrafrique", flag: "🇨🇫" },
  { code: "TD", name: "Tchad", flag: "🇹🇩" },
  { code: "GQ", name: "Guinée Équatoriale", flag: "🇬🇶" },
  { code: "ZA", name: "Afrique du Sud", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "SN", name: "Sénégal", flag: "🇸🇳" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BJ", name: "Bénin", flag: "🇧🇯" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "TZ", name: "Tanzanie", flag: "🇹🇿" },
  { code: "UG", name: "Ouganda", flag: "🇺🇬" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "ET", name: "Éthiopie", flag: "🇪🇹" },
  { code: "MA", name: "Maroc", flag: "🇲🇦" },
  { code: "DZ", name: "Algérie", flag: "🇩🇿" },
  { code: "TN", name: "Tunisie", flag: "🇹🇳" },
  { code: "EG", name: "Égypte", flag: "🇪🇬" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "BE", name: "Belgique", flag: "🇧🇪" },
  { code: "CH", name: "Suisse", flag: "🇨🇭" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪" },
  { code: "IT", name: "Italie", flag: "🇮🇹" },
  { code: "ES", name: "Espagne", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "US", name: "États-Unis", flag: "🇺🇸" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "BR", name: "Brésil", flag: "🇧🇷" },
  { code: "CN", name: "Chine", flag: "🇨🇳" },
  { code: "IN", name: "Inde", flag: "🇮🇳" },
  { code: "AE", name: "Émirats Arabes Unis", flag: "🇦🇪" },
  { code: "SA", name: "Arabie Saoudite", flag: "🇸🇦" },
  { code: "TR", name: "Turquie", flag: "🇹🇷" },
  { code: "RU", name: "Russie", flag: "🇷🇺" },
  { code: "JP", name: "Japon", flag: "🇯🇵" },
  { code: "KR", name: "Corée du Sud", flag: "🇰🇷" },
  { code: "AU", name: "Australie", flag: "🇦🇺" },
  { code: "OTHER", name: "Autre", flag: "🌍" },
];
